<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>微生活TS</title>
    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!-- bootstrap 3.0.2 -->
    <link href="/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <!-- font Awesome -->
    <link href="/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <!-- Ionicons -->
    <link href="/css/ionicons.min.css" rel="stylesheet" type="text/css" />
    <!-- Theme style -->
    <link href="/css/AdminLTE.css" rel="stylesheet" type="text/css" />
</head>
<body class="skin-blue">
    <header class="header">
        <a href="" class="logo">
            <!-- Add the class icon to your logo image or logo icon to add the margining -->
            微生活TS
        </a>
        <!-- Header Navbar: style can be found in header.less -->
        <nav class="navbar navbar-static-top" role="navigation">
            <!-- Sidebar toggle button-->
            <a href="#" class="navbar-btn sidebar-toggle" data-toggle="offcanvas" role="button">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <div class="navbar-right">
                <ul class="nav navbar-nav">
                    <li class="dropdown user user-menu">
                        <a href="#">
                            <i class="glyphicon glyphicon-user"></i>
                            <span>高华</span>
                        </a>
                    </li>
                    <li>
                        <a href="/user/reset">修改密码</a>
                    </li>
                    <li>
                        <a href="/user/logout">退出</a>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
</body>
</html>